CREATE user bdi2user;
CREATE database bdi2db;
ALTER USER bdi2user WITH PASSWORD '';
GRANT ALL PRIVILEGES ON DATABASE bdi2db to bdi2user;
ALTER DATABASE bdi2db OWNER TO bdi2user;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO bdi2user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO bdi2user;
-- Ensure future tables are also granted:
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO bdi2user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO bdi2user;